import type { LucideIcon } from "lucide-react";
import { CalendarDays, Compass, Sparkles, Star, Telescope } from "lucide-react";

export const PROGRAM_AGE_GROUPS = [
  { label: "5-7 ani", key: "5-7" },
  { label: "7-9 ani", key: "7-9" },
  { label: "9-11 ani", key: "9-11" },
] as const;

export type ProgramAgeGroupKey = (typeof PROGRAM_AGE_GROUPS)[number]["key"];

export type ProgramTimeSlot = {
  interval: string;
  activity: string;
};

export type ProgramDay = {
  title: string;
  key: string;
  icon: LucideIcon;
  schedules: Record<ProgramAgeGroupKey, ProgramTimeSlot[]>;
};

export const PROGRAM_DAYS: ProgramDay[] = [
  {
    title: "Ziua 1",
    key: "day1",
    icon: Sparkles,
    schedules: {
      "5-7": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00- 10:15", activity: "Găsește pe cineva care...\nMingea întrebărilor\n2 adevăruri și o minciună\nDacă aș fi..." },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Experimente chimice\nFacultatea de Inginerie Chimică și Biotehnologii" },
      { interval: "12:00 – 13:00", activity: "Plastilină\nBubble station\nTraseu motric\nMud kitchen\nCentru LEGO mic/mare" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități coordonate de Facultatea de Energetică" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "VOLEI Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Pictura, jocuri cu mingea, șotron" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "7-9": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00- 10:15", activity: "Mingea curioasă\nEu și tu (Cui îi place înghețata?)\nCutia magică" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Experimente chimice\nFacultatea de Inginerie Chimică și Biotehnologii" },
      { interval: "12:00 – 13:00", activity: "Water Engineering Lab\nFriendship Factory\nPuzzle/Logic Corner" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități coordonate de Facultatea de Energetică" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "VOLEI Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Desen liber, coarda" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "9-11": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00- 10:15", activity: "Găsește minciuna\nInsula pustie" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Experimente chimice\nFacultatea de Inginerie Chimică și Biotehnologii" },
      { interval: "12:00 – 13:00", activity: "VIP lounge, write/read corner, robo table games, 'ce ai scris in frunte?', Trivia" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități coordonate de Facultatea de Energetică" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "VOLEI Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Scris, citit, joaca in aer liber" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
    },
  },
  {
    title: "Ziua 2",
    key: "day2",
    icon: Compass,
    schedules: {
      "5-7": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Industrială și Robotică" },
      { interval: "12:00 – 13:00", activity: "fairy garden" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea\nInginerie Medicală" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "BASCHET Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Joacă în echipă, fuga cu sacii" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "7-9": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Industrială și Robotică" },
      { interval: "12:00 – 13:00", activity: "fairy garden" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea\nInginerie Medicală" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "BASCHET Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Joacă în echipă, fuga cu sacii" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "9-11": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Industrială și Robotică" },
      { interval: "12:00 – 13:00", activity: "fairy garden" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea\nInginerie Medicală" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "BASCHET Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Joacă în echipă, fuga cu sacii" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
    },
  },
  {
    title: "Ziua 3",
    key: "day3",
    icon: Star,
    schedules: {
      "5-7": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Electrică" },
      { interval: "12:00 – 13:00", activity: "Traseu motric" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea de Automatică" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "FOTBAL Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Table games" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "7-9": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Electrică" },
      { interval: "12:00 – 13:00", activity: "Lego, piscina bile, 'make our own hub'(elemente naturale)" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea de Automatică" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "FOTBAL Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Table games" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "9-11": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Electrică" },
      { interval: "12:00 – 13:00", activity: "Table games - smart games" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea de Automatică" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "FOTBAL Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Table games" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
    },
  },
  {
    title: "Ziua 4",
    key: "day4",
    icon: CalendarDays,
    schedules: {
      "5-7": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Mecanică și Mecatronică" },
      { interval: "12:00 – 13:00", activity: "Autoportret" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea de Inginerie Aerospațială" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "HANDBAL Știința București - joc și mișcare" },
      { interval: "17:00 - 17:30", activity: "Planetarium" },
      { interval: "17:15 -17:30", activity: "Activități de relaxare, joacă cu lut" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "7-9": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Mecanică și Mecatronică" },
      { interval: "12:00 – 13:00", activity: "Autoportret" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea de Inginerie Aerospațială" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "HANDBAL Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Activități de relaxare, puzzle, Lego" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "9-11": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00 - 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Inginerie Mecanică și Mecatronică" },
      { interval: "12:00 – 13:00", activity: "Autoportret" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Facultatea de Inginerie Aerospațială" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "HANDBAL Știința București - joc și mișcare" },
      { interval: "17:15 -17:30", activity: "Activități de relaxare, fișe" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
    },
  },
  {
    title: "Ziua 5",
    key: "day5",
    icon: Telescope,
    schedules: {
      "5-7": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00- 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Ingineria Sistemelor Biotehnice" },
      { interval: "12:00 – 13:00", activity: "Gânduri de rămas-bun" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Euronews/Proces simulat" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "ABSOLVIRE" },
      { interval: "17:15 -17:30", activity: "Party și poze de final" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "7-9": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00- 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Ingineria Sistemelor Biotehnice" },
      { interval: "12:00 - 12:30", activity: "Planetarium" },
      { interval: "12:00 – 13:00", activity: "Gânduri de rămas-bun" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Euronews/Proces simulat" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "ABSOLVIRE" },
      { interval: "17:15 -17:30", activity: "Party și poze de final" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
      "9-11": [
      { interval: "08:30- 9:00", activity: "Sosire copii, warm-up" },
      { interval: "9:00- 10:30", activity: "Activități de cunoaștere" },
      { interval: "10.15-10.30", activity: "Gustare" },
      { interval: "10.30 – 12:00", activity: "Activități susținute de Facultatea de Ingineria Sistemelor Biotehnice" },
      { interval: "12:00 – 13:00", activity: "Gânduri de rămas-bun" },
      { interval: "12:30 - 13:00", activity: "Planetarium" },
      { interval: "13:00 – 14:00", activity: "Prânz" },
      { interval: "14:00 – 15:30", activity: "Activități susținute de Euronews/Proces simulat" },
      { interval: "15:30 – 15:45", activity: "Gustare și hidratare" },
      { interval: "15:45 – 17:15", activity: "ABSOLVIRE" },
      { interval: "17:15 -17:30", activity: "Party și poze de final" },
      { interval: "17:30-18:00", activity: "Preluare copii" },
      ],
    },
  }
];
